# Generated by Django 2.0 on 2017-12-17 20:31

from django.db import migrations, models
import products.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', products.fields.LtreeField(db_index=True)),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', products.fields.LtreeField(db_index=True)),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
