# Generated by Django 2.0 on 2017-12-24 23:51

from django.db import migrations, models
import django.db.models.deletion
import products.fields


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_auto_20171218_2134'), ('products', '0003_auto_20171218_2244'), ('products', '0004_auto_20171224_2219'), ('products', '0005_auto_20171224_2230'), ('products', '0006_auto_20171224_2249'), ('products', '0007_auto_20171224_2255'), ('products', '0008_auto_20171224_2327'), ('products', '0009_auto_20171224_2328'), ('products', '0010_auto_20171224_2330'), ('products', '0011_auto_20171224_2340'), ('products', '0012_auto_20171224_2342')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', products.fields.LtreeField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', products.fields.LtreeField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Category')),
            ],
        ),
    ]
