# Generated by Django 2.0 on 2017-12-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='path',
            new_name='parent_path',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='parent_category',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='path',
            new_name='parent_path',
        ),
    ]
